version: "3.9"

services:
    django:
        image: django-docker:0.0.1
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports:
         - "8000:8000"

# version: "3.9"
   
# services:
#   db:
#     image: postgres
#     volumes:
#       - ./data/db:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=localhost
#       - POSTGRES_USER=sahil
#       - POSTGRES_PASSWORD=z0987
      
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/code
#     ports:
#       - "8000:8000"
    
#     environment:
#       - POSTGRES_NAME=sahil
#       - POSTGRES_USER=sahil
#       - POSTGRES_PASSWORD=z0987
#     depends_on:
#       - db