# Generated by Django 4.0.6 on 2022-07-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description1', models.TextField()),
                ('description2', models.TextField()),
                ('description3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Profile', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.BigIntegerField()),
            ],
        ),
    ]
