# Generated by Django 3.2.14 on 2022-07-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_date', models.CharField(max_length=255)),
                ('project_type', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
            ],
        ),
    ]
